<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>registro</title>
    <link rel="stylesheet" href="assets/css/estiloGeneral.css">
</head>
<body>
     <?php
    require_once __DIR__ . '/../partials/nav_bar.phtml';
    ?>
    
    <div class = 'logReg_segment'>

    <div class = 'logReg_segment2'>
    <h1>Register</h1>
    <?php if(!empty($error)) echo "<p style='color:red;'>$error</p>"; ?>
    <form action="?action=register" method="POST" class='form'>
        <label>Nombre: <input type="text" name="name" required></label><br>
        <label>Email: <input type="email" name="email" required></label><br>
        <label>Contraseña: <input type="password" name="password" required></label><br>
        <button type="submit">Registrarse</button>
    </form>
    <p>you have account? <a href="?action=login">Ingresar</a></p>
    </div>
    </div>
    <?php
    require_once __DIR__ . '/../partials/footer.phtml';
    ?>
</body>
</html>
