<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Gestión de Vehículos</title>
    <link rel="stylesheet" href="assets/css/estiloGeneral.css">
</head>
<body>

    <?php
    require_once __DIR__ . '/../../partials/nav_bar.phtml';
    ?>

    <main class= 'panel_main'>
    <h1>Panel de gestión de vehículos</h1>

    <nav class= 'nav_panel'>
        <ul class = 'ul_panel'>
            
                <li><a href="?action=vehiculos/create">Agregar nuevo vehículo</a></li>
                <li><a href="?action=vehiculos/editList">Editar vehículos</a></li>
                <li><a href="?action=vehiculos/deleteList">Eliminar vehículos</a></li>
           
        </ul>
    </nav>
    </main>
    <?php
    require_once __DIR__ . '/../../partials/footer.phtml';
    ?>
</body>
</html>
