<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Gestión de Vehículos</title>
    <link rel="stylesheet" href="assets/css/estiloGeneral.css">
</head>
<body>
    <?php
    require_once __DIR__ . '/../../partials/nav_bar.phtml';
    ?>
    <main class= 'panel_main'>    
    <h1>Panel de gestión de vehículos</h1>

    <nav class= 'nav_panel'>
        <ul class = 'ul_panel'>
            
                <li><a href="?action=panel/vehicle/create">Agregar nuevo vehículo</a></li>
                <li><a href="?action=panel/vehicle/list">Editar/eliminar vehículos</a></li>
           
        </ul>
    </nav>
    <div class='div_panel'>
    <h1>Administrar categorias</h1>
    <nav class= 'nav_panel'>
        <ul class = 'ul_panel'>
            
                <li><a href="?action=panel/category/create">Agregar nueva categoría</a></li>
                <li><a href="?action=panel/category/edit">Editar categorías</a></li>
                <li><a href="?action=panel/category/delete">Eliminar categorías</a></li>

           
        </ul>
    </nav>
    </div>
    </main>
    <?php
    require_once __DIR__ . '/../../partials/footer.phtml';
    ?>
</body>
</html>
